### ISSUE TITLE
TypeError: k is not a function

### ISSUE THREAD

**Issue by zhangchiqing** [garyb/purescript-debug#12]
The following code will compile, but throw in runtime.
```
module Main where

import Prelude
import Debug.Trace

main = do
  trace "Hello sailor!"
```

```
> pulp run

* Build successful.
'Hello sailor!'
/Users/leo/pure/debug/output/Debug.Trace/foreign.js:16
    return k({});
           ^

TypeError: k is not a function
    at Object.main (/Users/leo/pure/debug/output/Debug.Trace/foreign.js:16:12)
    at Object.<anonymous> (/private/var/folders/ll/xv5zmv7d20j8vbrz9hm0851h0000gn/T/pulp-run1161011-49195-s88cc.xsjj1yvi.js:1:79)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
* ERROR: Subcommand terminated with exit code 1
```

Environment:

```
▸ pulp -v
Pulp version 9.1.0
psc version 0.10.1 using /Users/leo/.nvm/versions/node/v6.9.1/bin/psc

▸ bower info purescript-debug
bower cached        https://github.com/garyb/purescript-debug.git#2.0.0
bower validate      2.0.0 against https://github.com/garyb/purescript-debug.git#*
```

**Comment by garyb** [comment]
This is a manifestation of the bug mentioned in https://github.com/purescript/purescript/issues/2086 - `main` is not an `Eff` here, as per `trace`'s type. Try adding a `main :: Eff _ Unit` annotation to see what I mean. `traceA` is probably the one you want for use in a `do`!

**Comment by zhangchiqing** [comment]
Thanks @garyb !

`traceA` works for me.

I was reading ["A good overview of Aff" in purescript-aff](https://github.com/slamdata/purescript-aff#see-also). It has an example, but doesn't compile. But it works if I change `trace` to `traceA`.

<img width="854" alt="screen shot 2016-11-11 at 7 48 41 am" src="https://cloud.githubusercontent.com/assets/811374/20220716/70fa4414-a7e3-11e6-9f56-ddcfc226b3fe.png">

I'm just curious what has been changed.

**Comment by garyb** [comment]
Ah ok! I think that `trace` refers to an old name for what is now `Control.Monad.Eff.Console.log`, or is a mistake in the slides :) I thought we renamed it a really long time ago.

**Comment by zhangchiqing** [comment]
Yeah, changing `trace` to `log` doesn't work. Using `traceA` works. I think is a mistake. Thanks @garyb .
