### ISSUE TITLE
Spy logs mutated map in its final state

### ISSUE THREAD

**Issue by ad-si** [garyb/purescript-debug#23]
I have a recursive function in which I call `spy` for a changing map. However, it all logs show the state of the map at the end. I guess this is because of JavaScript's object being passed by reference.
Can this be fixed? Otherwise there should be a warning in the documentation that this can happen.

**Comment by garyb** [comment]
Spy prints a value, so until the value exists it can't be printed - if you're building it recursively it doesn't exist until "the end", so this seems pretty normal?

Even if this wasn't the case, all of `-debug` is completely unsafe and has no behaviour guarantees, I think it goes without saying that things might be weird :smile:

**Comment by garyb** [comment]
Hmm actually, I think maybe I see what you're saying, I so rarely use mutable data structures that I didn't get what you mean by "changing"... if that's what you're talking about?

The logging by reference thing is something that Chrome does when the console is open, but I'm not sure about other browsers, and obviously it can't do that in Node.

**Comment by ad-si** [comment]
Yeah, that's what I'm talking about. Sorry, wasn't a particularly clear explanation from me 😅.

Oh no, I'm running the code on Node.js, that's why I think it's weird. Normally logging of mutable data structures over time should work.

**Comment by garyb** [comment]
Uh yeah, that's definitely weird! I don't know how that would even happen 🤯

**Comment by garyb** [comment]
Going to close this as it's perhaps a little stale now! And not heard any other reports of this.
