### ISSUE TITLE
Dynamic require makes build tools complain

### ISSUE THREAD

**Issue by natefaubion** [garyb/purescript-debug#6]
The recent update make bundling tools complain if you try to use purescript-debug due to the "dynamic" require.

**Comment by natefaubion** [comment]
And it will make it try to include utils, and a bunch of other weird stuff (even for the browser), and then tries to log with colors in the browser console, which ends up looking like garbage :stuck_out_tongue:

**Comment by garyb** [comment]
I thought this was fixed, but it's not. The current approach is enough to trip up Browserify but not webpack apparently...
