### ISSUE TITLE
Trace.js - no global value require (aliasing technique results in ReferenceError)

### ISSUE THREAD

**Issue by mgmeier** [garyb/purescript-debug#8]
In Trace.js you assume a defined require `var req = require`, which results in `ReferenceError: require is not defined` (browser console). Since `util` may remain undefined, wouldn't it make sense to check `require` directly instead of needlessly binding it to `req`before - especially since req isn't used any further?

I'm using purescript-0.8.5.0, building with bower + pulp + psc-bundle

**Comment by garyb** [comment]
We can't use a call to `require` directly, as then browserify or webpack pull in the `util` module from node. Interesting you're getting the `ReferenceError` though, I haven't seen that. What browser is raising the error?

**Comment by mgmeier** [comment]
FF 46.0.1 / OS X El Capitan 64bit

using a condition like `typeof require !== 'undefined'` does fix things for me, since typeof doesn't throw this particular error.

**Comment by garyb** [comment]
Ah yeah, that makes sense. It probably should throw in every browser actually, since strict mode is enabled. Could you submit a PR with that fix please? Or I can just do it, either way is fine by me. :smile:

**Comment by mgmeier** [comment]
Great. I can prepare a PR, no hassle.

**Comment by garyb** [comment]
Resolved by #9
